Guide user and prevent empty searches
UTDNebula/utd-trends pull request #231
Opened 2024-10-06 20:16 UTC by AbhiramTadepalli

## Overview

#215

Grey out search button text and show tooltip if user tries to empty search

## What Changed

Search button text is not white by default, and becomes white once the user selects at least 1 valid search term from autocomplete
Removed the alert from index.tsx that used to display above the search bar when the user tried to empty search
Transferred the text into a tooltip that pops up above the search button if the user clicks enter or the button without any search terms

2024-10-06 20:17 UTC, AbhiramTadepalli commented
Should the text be "Select a course or professor before searching" instead of "Select an option before searching"

2024-10-06 20:59 UTC, TyHil requested changes
The search bar still lets you search with a blank field on the dashboard, should make it not allow you like on the homepage?

Otherwise, left some comments

2024-10-06 20:59 UTC, TyHil commented on src/pages/index.tsx
>    }
can you remove this function if it does nothing

2024-10-06 20:59 UTC, TyHil commented on src/components/common/SearchBar/searchBar.tsx
> +              : 'shrink-0 normal-case bg-royal hover:bg-royalDark'
can this be:

`'shrink-0 normal-case bg-royal hover:bg-royalDark' + (value.length == 0 ? ' text-cornflower-100' : '')`

so it's more obvious what's changing

2024-10-06 20:59 UTC, TyHil commented on src/components/common/SearchBar/searchBar.tsx
> +    setErrorTooltip(!newValue.length); //Check if tooltip needs to be displayed
the tool tip never goes away on the homepage, not sure why, seems this should do it.

2024-10-06 20:59 UTC, TyHil commented
> Should the text be "Select a course or professor before searching" instead of "Select an option before searching"?

That sounds good, fine with either

2024-10-07 05:25 UTC, AbhiramTadepalli commented
> The search bar still lets you search with a blank field on the dashboard, should make it not allow you like on the homepage?
> 
> Otherwise, left some comments

Fixed this and everything else, can you check?

2024-10-07 05:26 UTC, AbhiramTadepalli commented
The search button is a _little_ shorter than the searchbar, is that intentional?

2024-10-07 05:39 UTC, TyHil commented
Looks all good to me!

> The search button is a _little_ shorter than the searchbar, is that intentional?

Unintentional, just mui default button height

2024-10-07 05:40 UTC, TyHil approved these changes

2024-10-07 06:00 UTC, AbhiramTadepalli commented
> Unintentional, just mui default button height

should I change?

2024-10-07 06:18 UTC, merged