211 feature request add a notification indicating the number of results in the compare tab
UTDNebula/utd-trends pull request #275
Opened 2024-10-23 21:44 UTC by Shivhare-Ayush

## Overview

List the GitHub issues containing the issues relevant to this pull request.

issue #211 

## What Changed

Files changed: Index, Carousel, and TabNavMenu 
Added a badge to TabNavMenu and passed data from Index to Carousel to TabNavMenu

2024-10-31 11:55 UTC, AbhiramTadepalli commented
@Shivhare-Ayush did you manually change these or were you on an outdated branch?

2024-10-31 12:00 UTC, AbhiramTadepalli requested changes
The rest of this looks great, but keep some of the tab nav logic we had in `carousel.tsx`

2024-10-31 12:00 UTC, AbhiramTadepalli commented on src/components/common/Carousel/carousel.tsx
> -  if (Array.isArray(children) && currentCard >= children.length) {
Is there a reason you needed to remove this line? We need it (previous issue) to fix a carousel tab nav bug on a new search that removes tabs

2024-10-31 12:00 UTC, AbhiramTadepalli commented on src/components/common/Carousel/carousel.tsx
> +    setCard(currentCard + displacement);
Same here. This loops it around in some scenarios so the carousel doesn't become empty https://github.com/UTDNebula/utd-trends/issues/176

2024-10-31 12:00 UTC, AbhiramTadepalli commented on src/components/common/Carousel/carousel.tsx
> +            {Array.isArray(children) ? children[currentCard] : children}
@TyHil what does this part do?

2024-11-02 01:57 UTC, TyHil commented
I think when I was helping revert some changes we accidentally checked out an earlier version of `src/components/common/Carousel/carousel.tsx`. Just made a commit adding those changes back so this should be good to go.

2024-11-02 01:57 UTC, TyHil commented on src/components/common/Carousel/carousel.tsx
> +            {Array.isArray(children) ? children[currentCard] : children}
this is what keeps the cards mounted by hiding them instead of removing them

2024-11-02 02:24 UTC, AbhiramTadepalli approved these changes
Great

2024-11-02 02:24 UTC, merged